### PR TITLE
test

### PR DESCRIPTION
**Pull request by FlorianBeerRB**

### CODE REVIEW

**Comment by FlorianBeerRB** [comment]
Please check https://github.com/LieberLieber/LemonTree.Automation.Workflows/actions/runs/2074532747
Exit code 9

**Comment by danielsiegl** [comment]
public enum Automation
                  {
                        ErrorCmdParameter = -1, //Parsing error of command line parameter
                        Success = 0, // Successful merge
                                         //Avoid 1 used in Desktop
                        ErrorDiff = 2, //Diff error
                        ErrorMerge = 3, // Merge failed
                                               //Avoid 4 used in Desktop
                        ErrorQuickPublish = 5, //Most likely wrong GUID
                        ErrorLicense = 6, // license error
                                                 //Avoid 7 used in Desktop
                        NoDifferencesFound = 8, //for future use
                        ErrorWritingOutFile = 9, // output could not be written
                        ErrorIdenticalFileNames = 10, //if model and outputfile are the same - danger to override model
                        ErrorImport = 11, //Not all packages could be imported
                        IntegrityViolationsNoneFatal = 12, //the Check for consistency has found one or more inconsistencies.
                        IntegrityViolationsFatal = 13, //the Check for consistency has found one or more fatal inconsistencies.
                        ErrorPublish = 14 //Something went wrong during publish
                  }

Von: Florian Beer ***@***.***>
Gesendet: Freitag, 1. April 2022 03:25
An: LieberLieber/LemonTree.Automation.Workflows ***@***.***>
Cc: Daniel Siegl (LieberLieber) ***@***.***>; Review requested ***@***.***>
Betreff: Re: [LieberLieber/LemonTree.Automation.Workflows] test (PR #42)


Please check https://github.com/LieberLieber/LemonTree.Automation.Workflows/actions/runs/2074532747
Exit code 9

**Comment by danielsiegl** [comment]
I guess the problem is related to the LieberLieber/ directory not found - we are checking this internally @paulkronabethleitner pls have a look ;)

**Comment by paulkronabethleitner** [comment]
exitcode 9 - ErrorWritingOutFile handles both --out and --sfs, seems like the sfs file could not be written. Filename looks to be okay, so insufficient permissions to write would be my guess.

**Pull request closed without merging**
