### PR TITLE
Update on Model for Florian

### PR DESCRIPTION
**Pull request by danielsiegl**

### CODE REVIEW

**Comment by FlorianBeerRB** [comment]
/rebase/

**Comment by FlorianBeerRB** [comment]
test

**Comment by FlorianBeerRB** [comment]
test

**Comment by FlorianBeerRB** [comment]
test

**Comment by FlorianBeerRB** [comment]
test

**Comment by FlorianBeerRB** [comment]
test

**Comment by danielsiegl** [comment]
/rebase/

**Comment by danielsiegl** [comment]
/rebase/

**Comment by danielsiegl** [comment]
/rebase/

**Comment by FlorianBeerRB** [comment]
/rebase/

**Comment by FlorianBeerRB** [comment]
/rebase/

**Comment by FlorianBeerRB** [comment]
/rebase/

**Comment by FlorianBeerRB** [comment]
/rebase/

**Comment by FlorianBeerRB** [comment]
/rebase/

**Comment by FlorianBeerRB** [comment]
/rebase/

**Comment by FlorianBeerRB** [comment]
/rebase/

**Comment by FlorianBeerRB** [comment]
/rebase/

**Comment by FlorianBeerRB** [comment]
/rebase/

**Comment by danielsiegl** [comment]
Why do we need this new Generalzaition!
image

should be named anyway

**Comment by danielsiegl** [comment]
image

**Pull request closed without merging**
